Component dialog
Neos1/zeroone pull request #49
Opened 2019-12-03 02:13 UTC by pzyryanov1995

2019-12-04 02:28 UTC, masteralx requested changes

2019-12-04 02:28 UTC, masteralx commented on src/components/Dialog/DefinetelyAgree.js
> +@withTranslation()
withTranslation upper

2019-12-04 02:28 UTC, masteralx commented on src/components/Dialog/AgreedMessage.js
> +import React from 'react';
- Move  icon from dialog
- Create message component
- Remove Agree Dialog, reject Dialog

2019-12-04 02:28 UTC, masteralx commented on src/components/Dialog/DefaultDialogFooter.js
> +import React from 'react';
Check is it used anywhere

2019-12-04 02:28 UTC, masteralx commented on src/components/Dialog/TokenTransferSuccess.js
> +import React from 'react';
Separate message

2019-12-04 02:28 UTC, masteralx commented on src/stores/DialogStore/DialogItemModel.js
> +
add jsdoc comments

2019-12-04 02:28 UTC, masteralx commented on src/stores/DialogStore/DialogStore.js
> +import {
jsdoc comments

2019-12-04 07:49 UTC, pzyryanov1995 commented on src/components/Dialog/DefinetelyAgree.js
> +@withTranslation()
fixed

2019-12-04 07:49 UTC, pzyryanov1995 commented on src/components/Dialog/AgreedMessage.js
> +import React from 'react';
fixed

2019-12-04 07:50 UTC, pzyryanov1995 commented on src/components/Dialog/DefaultDialogFooter.js
> +import React from 'react';
it's used in basic dialog by default

2019-12-04 08:14 UTC, pzyryanov1995 commented on src/components/Dialog/TokenTransferSuccess.js
> +import React from 'react';
fixed

2019-12-04 08:14 UTC, pzyryanov1995 commented on src/stores/DialogStore/DialogStore.js
> +import {
fixed

2019-12-05 02:11 UTC, masteralx requested changes

2019-12-05 02:11 UTC, masteralx commented on src/stores/DialogStore/DialogStore.js
> +     * @param {object} options options for new dialog
specify object

2019-12-05 02:11 UTC, masteralx commented on src/stores/DialogStore/DialogItemModel.js
> +  constructor(name, options) {
describe params

2019-12-05 02:23 UTC, pzyryanov1995 commented on src/stores/DialogStore/DialogStore.js
> +     * @param {object} options options for new dialog
upd

2019-12-05 02:23 UTC, pzyryanov1995 commented on src/stores/DialogStore/DialogItemModel.js
> +  constructor(name, options) {
upd

2019-12-05 02:27 UTC, masteralx approved these changes

2019-12-05 02:28 UTC, merged